// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.aristoula.persistence.messages.proto;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.aristoula.persistence.messages.proto.CounterOp}
   */
  public enum CounterOp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INCREMENT = 0;</code>
     */
    INCREMENT(0),
    /**
     * <code>DECREMENT = 1;</code>
     */
    DECREMENT(1),
    ;

    /**
     * <code>INCREMENT = 0;</code>
     */
    public static final int INCREMENT_VALUE = 0;
    /**
     * <code>DECREMENT = 1;</code>
     */
    public static final int DECREMENT_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CounterOp valueOf(int value) {
      return forNumber(value);
    }

    public static CounterOp forNumber(int value) {
      switch (value) {
        case 0: return INCREMENT;
        case 1: return DECREMENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CounterOp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CounterOp> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CounterOp>() {
            public CounterOp findValueByNumber(int number) {
              return CounterOp.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.aristoula.persistence.messages.proto.Messages.getDescriptor().getEnumTypes().get(0);
    }

    private static final CounterOp[] VALUES = values();

    public static CounterOp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CounterOp(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.aristoula.persistence.messages.proto.CounterOp)
  }

  public interface EntityEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aristoula.persistence.messages.proto.EntityEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional .com.aristoula.persistence.messages.proto.CounterOp payload = 2;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional .com.aristoula.persistence.messages.proto.CounterOp payload = 2;</code>
     */
    com.aristoula.persistence.messages.proto.Messages.CounterOp getPayload();

    /**
     * <code>optional string ohField = 3;</code>
     */
    boolean hasOhField();
    /**
     * <code>optional string ohField = 3;</code>
     */
    java.lang.String getOhField();
    /**
     * <code>optional string ohField = 3;</code>
     */
    com.google.protobuf.ByteString
        getOhFieldBytes();

    /**
     * <code>optional int64 someOtherShit = 4;</code>
     */
    boolean hasSomeOtherShit();
    /**
     * <code>optional int64 someOtherShit = 4;</code>
     */
    long getSomeOtherShit();

    /**
     * <code>optional string MoreShitToCome = 5;</code>
     */
    boolean hasMoreShitToCome();
    /**
     * <code>optional string MoreShitToCome = 5;</code>
     */
    java.lang.String getMoreShitToCome();
    /**
     * <code>optional string MoreShitToCome = 5;</code>
     */
    com.google.protobuf.ByteString
        getMoreShitToComeBytes();
  }
  /**
   * Protobuf type {@code com.aristoula.persistence.messages.proto.EntityEnvelope}
   */
  public  static final class EntityEnvelope extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aristoula.persistence.messages.proto.EntityEnvelope)
      EntityEnvelopeOrBuilder {
    // Use EntityEnvelope.newBuilder() to construct.
    private EntityEnvelope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityEnvelope() {
      id_ = 0L;
      payload_ = 0;
      ohField_ = "";
      someOtherShit_ = 0L;
      moreShitToCome_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntityEnvelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.aristoula.persistence.messages.proto.Messages.CounterOp value = com.aristoula.persistence.messages.proto.Messages.CounterOp.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                payload_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              ohField_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              someOtherShit_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              moreShitToCome_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aristoula.persistence.messages.proto.Messages.EntityEnvelope.class, com.aristoula.persistence.messages.proto.Messages.EntityEnvelope.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private int payload_;
    /**
     * <code>optional .com.aristoula.persistence.messages.proto.CounterOp payload = 2;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.aristoula.persistence.messages.proto.CounterOp payload = 2;</code>
     */
    public com.aristoula.persistence.messages.proto.Messages.CounterOp getPayload() {
      com.aristoula.persistence.messages.proto.Messages.CounterOp result = com.aristoula.persistence.messages.proto.Messages.CounterOp.valueOf(payload_);
      return result == null ? com.aristoula.persistence.messages.proto.Messages.CounterOp.INCREMENT : result;
    }

    public static final int OHFIELD_FIELD_NUMBER = 3;
    private volatile java.lang.Object ohField_;
    /**
     * <code>optional string ohField = 3;</code>
     */
    public boolean hasOhField() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ohField = 3;</code>
     */
    public java.lang.String getOhField() {
      java.lang.Object ref = ohField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ohField_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ohField = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOhFieldBytes() {
      java.lang.Object ref = ohField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ohField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOMEOTHERSHIT_FIELD_NUMBER = 4;
    private long someOtherShit_;
    /**
     * <code>optional int64 someOtherShit = 4;</code>
     */
    public boolean hasSomeOtherShit() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 someOtherShit = 4;</code>
     */
    public long getSomeOtherShit() {
      return someOtherShit_;
    }

    public static final int MORESHITTOCOME_FIELD_NUMBER = 5;
    private volatile java.lang.Object moreShitToCome_;
    /**
     * <code>optional string MoreShitToCome = 5;</code>
     */
    public boolean hasMoreShitToCome() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string MoreShitToCome = 5;</code>
     */
    public java.lang.String getMoreShitToCome() {
      java.lang.Object ref = moreShitToCome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          moreShitToCome_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string MoreShitToCome = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMoreShitToComeBytes() {
      java.lang.Object ref = moreShitToCome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moreShitToCome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, payload_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ohField_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, someOtherShit_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, moreShitToCome_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, payload_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ohField_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, someOtherShit_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, moreShitToCome_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aristoula.persistence.messages.proto.Messages.EntityEnvelope)) {
        return super.equals(obj);
      }
      com.aristoula.persistence.messages.proto.Messages.EntityEnvelope other = (com.aristoula.persistence.messages.proto.Messages.EntityEnvelope) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasPayload() == other.hasPayload());
      if (hasPayload()) {
        result = result && payload_ == other.payload_;
      }
      result = result && (hasOhField() == other.hasOhField());
      if (hasOhField()) {
        result = result && getOhField()
            .equals(other.getOhField());
      }
      result = result && (hasSomeOtherShit() == other.hasSomeOtherShit());
      if (hasSomeOtherShit()) {
        result = result && (getSomeOtherShit()
            == other.getSomeOtherShit());
      }
      result = result && (hasMoreShitToCome() == other.hasMoreShitToCome());
      if (hasMoreShitToCome()) {
        result = result && getMoreShitToCome()
            .equals(other.getMoreShitToCome());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + payload_;
      }
      if (hasOhField()) {
        hash = (37 * hash) + OHFIELD_FIELD_NUMBER;
        hash = (53 * hash) + getOhField().hashCode();
      }
      if (hasSomeOtherShit()) {
        hash = (37 * hash) + SOMEOTHERSHIT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSomeOtherShit());
      }
      if (hasMoreShitToCome()) {
        hash = (37 * hash) + MORESHITTOCOME_FIELD_NUMBER;
        hash = (53 * hash) + getMoreShitToCome().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aristoula.persistence.messages.proto.Messages.EntityEnvelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aristoula.persistence.messages.proto.EntityEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aristoula.persistence.messages.proto.EntityEnvelope)
        com.aristoula.persistence.messages.proto.Messages.EntityEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aristoula.persistence.messages.proto.Messages.EntityEnvelope.class, com.aristoula.persistence.messages.proto.Messages.EntityEnvelope.Builder.class);
      }

      // Construct using com.aristoula.persistence.messages.proto.Messages.EntityEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ohField_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        someOtherShit_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        moreShitToCome_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_descriptor;
      }

      public com.aristoula.persistence.messages.proto.Messages.EntityEnvelope getDefaultInstanceForType() {
        return com.aristoula.persistence.messages.proto.Messages.EntityEnvelope.getDefaultInstance();
      }

      public com.aristoula.persistence.messages.proto.Messages.EntityEnvelope build() {
        com.aristoula.persistence.messages.proto.Messages.EntityEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aristoula.persistence.messages.proto.Messages.EntityEnvelope buildPartial() {
        com.aristoula.persistence.messages.proto.Messages.EntityEnvelope result = new com.aristoula.persistence.messages.proto.Messages.EntityEnvelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ohField_ = ohField_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.someOtherShit_ = someOtherShit_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.moreShitToCome_ = moreShitToCome_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aristoula.persistence.messages.proto.Messages.EntityEnvelope) {
          return mergeFrom((com.aristoula.persistence.messages.proto.Messages.EntityEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aristoula.persistence.messages.proto.Messages.EntityEnvelope other) {
        if (other == com.aristoula.persistence.messages.proto.Messages.EntityEnvelope.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasOhField()) {
          bitField0_ |= 0x00000004;
          ohField_ = other.ohField_;
          onChanged();
        }
        if (other.hasSomeOtherShit()) {
          setSomeOtherShit(other.getSomeOtherShit());
        }
        if (other.hasMoreShitToCome()) {
          bitField0_ |= 0x00000010;
          moreShitToCome_ = other.moreShitToCome_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aristoula.persistence.messages.proto.Messages.EntityEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aristoula.persistence.messages.proto.Messages.EntityEnvelope) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int payload_ = 0;
      /**
       * <code>optional .com.aristoula.persistence.messages.proto.CounterOp payload = 2;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.aristoula.persistence.messages.proto.CounterOp payload = 2;</code>
       */
      public com.aristoula.persistence.messages.proto.Messages.CounterOp getPayload() {
        com.aristoula.persistence.messages.proto.Messages.CounterOp result = com.aristoula.persistence.messages.proto.Messages.CounterOp.valueOf(payload_);
        return result == null ? com.aristoula.persistence.messages.proto.Messages.CounterOp.INCREMENT : result;
      }
      /**
       * <code>optional .com.aristoula.persistence.messages.proto.CounterOp payload = 2;</code>
       */
      public Builder setPayload(com.aristoula.persistence.messages.proto.Messages.CounterOp value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        payload_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.aristoula.persistence.messages.proto.CounterOp payload = 2;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ohField_ = "";
      /**
       * <code>optional string ohField = 3;</code>
       */
      public boolean hasOhField() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ohField = 3;</code>
       */
      public java.lang.String getOhField() {
        java.lang.Object ref = ohField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ohField_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ohField = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOhFieldBytes() {
        java.lang.Object ref = ohField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ohField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ohField = 3;</code>
       */
      public Builder setOhField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ohField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ohField = 3;</code>
       */
      public Builder clearOhField() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ohField_ = getDefaultInstance().getOhField();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ohField = 3;</code>
       */
      public Builder setOhFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ohField_ = value;
        onChanged();
        return this;
      }

      private long someOtherShit_ ;
      /**
       * <code>optional int64 someOtherShit = 4;</code>
       */
      public boolean hasSomeOtherShit() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 someOtherShit = 4;</code>
       */
      public long getSomeOtherShit() {
        return someOtherShit_;
      }
      /**
       * <code>optional int64 someOtherShit = 4;</code>
       */
      public Builder setSomeOtherShit(long value) {
        bitField0_ |= 0x00000008;
        someOtherShit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 someOtherShit = 4;</code>
       */
      public Builder clearSomeOtherShit() {
        bitField0_ = (bitField0_ & ~0x00000008);
        someOtherShit_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object moreShitToCome_ = "";
      /**
       * <code>optional string MoreShitToCome = 5;</code>
       */
      public boolean hasMoreShitToCome() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string MoreShitToCome = 5;</code>
       */
      public java.lang.String getMoreShitToCome() {
        java.lang.Object ref = moreShitToCome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            moreShitToCome_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string MoreShitToCome = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMoreShitToComeBytes() {
        java.lang.Object ref = moreShitToCome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          moreShitToCome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MoreShitToCome = 5;</code>
       */
      public Builder setMoreShitToCome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        moreShitToCome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MoreShitToCome = 5;</code>
       */
      public Builder clearMoreShitToCome() {
        bitField0_ = (bitField0_ & ~0x00000010);
        moreShitToCome_ = getDefaultInstance().getMoreShitToCome();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MoreShitToCome = 5;</code>
       */
      public Builder setMoreShitToComeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        moreShitToCome_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.aristoula.persistence.messages.proto.EntityEnvelope)
    }

    // @@protoc_insertion_point(class_scope:com.aristoula.persistence.messages.proto.EntityEnvelope)
    private static final com.aristoula.persistence.messages.proto.Messages.EntityEnvelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aristoula.persistence.messages.proto.Messages.EntityEnvelope();
    }

    public static com.aristoula.persistence.messages.proto.Messages.EntityEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EntityEnvelope>
        PARSER = new com.google.protobuf.AbstractParser<EntityEnvelope>() {
      public EntityEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EntityEnvelope(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntityEnvelope> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EntityEnvelope> getParserForType() {
      return PARSER;
    }

    public com.aristoula.persistence.messages.proto.Messages.EntityEnvelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CounterChangedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aristoula.persistence.messages.proto.CounterChanged)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 delta = 1;</code>
     */
    boolean hasDelta();
    /**
     * <code>optional int32 delta = 1;</code>
     */
    int getDelta();

    /**
     * <code>optional string anotherField = 2;</code>
     */
    boolean hasAnotherField();
    /**
     * <code>optional string anotherField = 2;</code>
     */
    java.lang.String getAnotherField();
    /**
     * <code>optional string anotherField = 2;</code>
     */
    com.google.protobuf.ByteString
        getAnotherFieldBytes();
  }
  /**
   * Protobuf type {@code com.aristoula.persistence.messages.proto.CounterChanged}
   */
  public  static final class CounterChanged extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aristoula.persistence.messages.proto.CounterChanged)
      CounterChangedOrBuilder {
    // Use CounterChanged.newBuilder() to construct.
    private CounterChanged(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CounterChanged() {
      delta_ = 0;
      anotherField_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CounterChanged(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              delta_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              anotherField_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_CounterChanged_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_CounterChanged_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aristoula.persistence.messages.proto.Messages.CounterChanged.class, com.aristoula.persistence.messages.proto.Messages.CounterChanged.Builder.class);
    }

    private int bitField0_;
    public static final int DELTA_FIELD_NUMBER = 1;
    private int delta_;
    /**
     * <code>optional int32 delta = 1;</code>
     */
    public boolean hasDelta() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 delta = 1;</code>
     */
    public int getDelta() {
      return delta_;
    }

    public static final int ANOTHERFIELD_FIELD_NUMBER = 2;
    private volatile java.lang.Object anotherField_;
    /**
     * <code>optional string anotherField = 2;</code>
     */
    public boolean hasAnotherField() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string anotherField = 2;</code>
     */
    public java.lang.String getAnotherField() {
      java.lang.Object ref = anotherField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          anotherField_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string anotherField = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAnotherFieldBytes() {
      java.lang.Object ref = anotherField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        anotherField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, delta_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, anotherField_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, delta_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, anotherField_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aristoula.persistence.messages.proto.Messages.CounterChanged)) {
        return super.equals(obj);
      }
      com.aristoula.persistence.messages.proto.Messages.CounterChanged other = (com.aristoula.persistence.messages.proto.Messages.CounterChanged) obj;

      boolean result = true;
      result = result && (hasDelta() == other.hasDelta());
      if (hasDelta()) {
        result = result && (getDelta()
            == other.getDelta());
      }
      result = result && (hasAnotherField() == other.hasAnotherField());
      if (hasAnotherField()) {
        result = result && getAnotherField()
            .equals(other.getAnotherField());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDelta()) {
        hash = (37 * hash) + DELTA_FIELD_NUMBER;
        hash = (53 * hash) + getDelta();
      }
      if (hasAnotherField()) {
        hash = (37 * hash) + ANOTHERFIELD_FIELD_NUMBER;
        hash = (53 * hash) + getAnotherField().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aristoula.persistence.messages.proto.Messages.CounterChanged prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aristoula.persistence.messages.proto.CounterChanged}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aristoula.persistence.messages.proto.CounterChanged)
        com.aristoula.persistence.messages.proto.Messages.CounterChangedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_CounterChanged_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_CounterChanged_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aristoula.persistence.messages.proto.Messages.CounterChanged.class, com.aristoula.persistence.messages.proto.Messages.CounterChanged.Builder.class);
      }

      // Construct using com.aristoula.persistence.messages.proto.Messages.CounterChanged.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        delta_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        anotherField_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_CounterChanged_descriptor;
      }

      public com.aristoula.persistence.messages.proto.Messages.CounterChanged getDefaultInstanceForType() {
        return com.aristoula.persistence.messages.proto.Messages.CounterChanged.getDefaultInstance();
      }

      public com.aristoula.persistence.messages.proto.Messages.CounterChanged build() {
        com.aristoula.persistence.messages.proto.Messages.CounterChanged result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aristoula.persistence.messages.proto.Messages.CounterChanged buildPartial() {
        com.aristoula.persistence.messages.proto.Messages.CounterChanged result = new com.aristoula.persistence.messages.proto.Messages.CounterChanged(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.delta_ = delta_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.anotherField_ = anotherField_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aristoula.persistence.messages.proto.Messages.CounterChanged) {
          return mergeFrom((com.aristoula.persistence.messages.proto.Messages.CounterChanged)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aristoula.persistence.messages.proto.Messages.CounterChanged other) {
        if (other == com.aristoula.persistence.messages.proto.Messages.CounterChanged.getDefaultInstance()) return this;
        if (other.hasDelta()) {
          setDelta(other.getDelta());
        }
        if (other.hasAnotherField()) {
          bitField0_ |= 0x00000002;
          anotherField_ = other.anotherField_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aristoula.persistence.messages.proto.Messages.CounterChanged parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aristoula.persistence.messages.proto.Messages.CounterChanged) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int delta_ ;
      /**
       * <code>optional int32 delta = 1;</code>
       */
      public boolean hasDelta() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 delta = 1;</code>
       */
      public int getDelta() {
        return delta_;
      }
      /**
       * <code>optional int32 delta = 1;</code>
       */
      public Builder setDelta(int value) {
        bitField0_ |= 0x00000001;
        delta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 delta = 1;</code>
       */
      public Builder clearDelta() {
        bitField0_ = (bitField0_ & ~0x00000001);
        delta_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object anotherField_ = "";
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public boolean hasAnotherField() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public java.lang.String getAnotherField() {
        java.lang.Object ref = anotherField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            anotherField_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAnotherFieldBytes() {
        java.lang.Object ref = anotherField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          anotherField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public Builder setAnotherField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        anotherField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public Builder clearAnotherField() {
        bitField0_ = (bitField0_ & ~0x00000002);
        anotherField_ = getDefaultInstance().getAnotherField();
        onChanged();
        return this;
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public Builder setAnotherFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        anotherField_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.aristoula.persistence.messages.proto.CounterChanged)
    }

    // @@protoc_insertion_point(class_scope:com.aristoula.persistence.messages.proto.CounterChanged)
    private static final com.aristoula.persistence.messages.proto.Messages.CounterChanged DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aristoula.persistence.messages.proto.Messages.CounterChanged();
    }

    public static com.aristoula.persistence.messages.proto.Messages.CounterChanged getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CounterChanged>
        PARSER = new com.google.protobuf.AbstractParser<CounterChanged>() {
      public CounterChanged parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CounterChanged(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CounterChanged> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CounterChanged> getParserForType() {
      return PARSER;
    }

    public com.aristoula.persistence.messages.proto.Messages.CounterChanged getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aristoula.persistence.messages.proto.Get)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 counterId = 1;</code>
     */
    boolean hasCounterId();
    /**
     * <code>optional int64 counterId = 1;</code>
     */
    long getCounterId();

    /**
     * <code>optional string anotherField = 2;</code>
     */
    boolean hasAnotherField();
    /**
     * <code>optional string anotherField = 2;</code>
     */
    java.lang.String getAnotherField();
    /**
     * <code>optional string anotherField = 2;</code>
     */
    com.google.protobuf.ByteString
        getAnotherFieldBytes();
  }
  /**
   * Protobuf type {@code com.aristoula.persistence.messages.proto.Get}
   */
  public  static final class Get extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aristoula.persistence.messages.proto.Get)
      GetOrBuilder {
    // Use Get.newBuilder() to construct.
    private Get(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Get() {
      counterId_ = 0L;
      anotherField_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Get(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              counterId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              anotherField_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_Get_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_Get_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aristoula.persistence.messages.proto.Messages.Get.class, com.aristoula.persistence.messages.proto.Messages.Get.Builder.class);
    }

    private int bitField0_;
    public static final int COUNTERID_FIELD_NUMBER = 1;
    private long counterId_;
    /**
     * <code>optional int64 counterId = 1;</code>
     */
    public boolean hasCounterId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 counterId = 1;</code>
     */
    public long getCounterId() {
      return counterId_;
    }

    public static final int ANOTHERFIELD_FIELD_NUMBER = 2;
    private volatile java.lang.Object anotherField_;
    /**
     * <code>optional string anotherField = 2;</code>
     */
    public boolean hasAnotherField() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string anotherField = 2;</code>
     */
    public java.lang.String getAnotherField() {
      java.lang.Object ref = anotherField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          anotherField_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string anotherField = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAnotherFieldBytes() {
      java.lang.Object ref = anotherField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        anotherField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, counterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, anotherField_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, counterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, anotherField_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aristoula.persistence.messages.proto.Messages.Get)) {
        return super.equals(obj);
      }
      com.aristoula.persistence.messages.proto.Messages.Get other = (com.aristoula.persistence.messages.proto.Messages.Get) obj;

      boolean result = true;
      result = result && (hasCounterId() == other.hasCounterId());
      if (hasCounterId()) {
        result = result && (getCounterId()
            == other.getCounterId());
      }
      result = result && (hasAnotherField() == other.hasAnotherField());
      if (hasAnotherField()) {
        result = result && getAnotherField()
            .equals(other.getAnotherField());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCounterId()) {
        hash = (37 * hash) + COUNTERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCounterId());
      }
      if (hasAnotherField()) {
        hash = (37 * hash) + ANOTHERFIELD_FIELD_NUMBER;
        hash = (53 * hash) + getAnotherField().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aristoula.persistence.messages.proto.Messages.Get parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aristoula.persistence.messages.proto.Messages.Get parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aristoula.persistence.messages.proto.Messages.Get prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aristoula.persistence.messages.proto.Get}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aristoula.persistence.messages.proto.Get)
        com.aristoula.persistence.messages.proto.Messages.GetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_Get_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_Get_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aristoula.persistence.messages.proto.Messages.Get.class, com.aristoula.persistence.messages.proto.Messages.Get.Builder.class);
      }

      // Construct using com.aristoula.persistence.messages.proto.Messages.Get.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        counterId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        anotherField_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aristoula.persistence.messages.proto.Messages.internal_static_com_aristoula_persistence_messages_proto_Get_descriptor;
      }

      public com.aristoula.persistence.messages.proto.Messages.Get getDefaultInstanceForType() {
        return com.aristoula.persistence.messages.proto.Messages.Get.getDefaultInstance();
      }

      public com.aristoula.persistence.messages.proto.Messages.Get build() {
        com.aristoula.persistence.messages.proto.Messages.Get result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aristoula.persistence.messages.proto.Messages.Get buildPartial() {
        com.aristoula.persistence.messages.proto.Messages.Get result = new com.aristoula.persistence.messages.proto.Messages.Get(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.counterId_ = counterId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.anotherField_ = anotherField_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aristoula.persistence.messages.proto.Messages.Get) {
          return mergeFrom((com.aristoula.persistence.messages.proto.Messages.Get)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aristoula.persistence.messages.proto.Messages.Get other) {
        if (other == com.aristoula.persistence.messages.proto.Messages.Get.getDefaultInstance()) return this;
        if (other.hasCounterId()) {
          setCounterId(other.getCounterId());
        }
        if (other.hasAnotherField()) {
          bitField0_ |= 0x00000002;
          anotherField_ = other.anotherField_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aristoula.persistence.messages.proto.Messages.Get parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aristoula.persistence.messages.proto.Messages.Get) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long counterId_ ;
      /**
       * <code>optional int64 counterId = 1;</code>
       */
      public boolean hasCounterId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 counterId = 1;</code>
       */
      public long getCounterId() {
        return counterId_;
      }
      /**
       * <code>optional int64 counterId = 1;</code>
       */
      public Builder setCounterId(long value) {
        bitField0_ |= 0x00000001;
        counterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 counterId = 1;</code>
       */
      public Builder clearCounterId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        counterId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object anotherField_ = "";
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public boolean hasAnotherField() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public java.lang.String getAnotherField() {
        java.lang.Object ref = anotherField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            anotherField_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAnotherFieldBytes() {
        java.lang.Object ref = anotherField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          anotherField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public Builder setAnotherField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        anotherField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public Builder clearAnotherField() {
        bitField0_ = (bitField0_ & ~0x00000002);
        anotherField_ = getDefaultInstance().getAnotherField();
        onChanged();
        return this;
      }
      /**
       * <code>optional string anotherField = 2;</code>
       */
      public Builder setAnotherFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        anotherField_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.aristoula.persistence.messages.proto.Get)
    }

    // @@protoc_insertion_point(class_scope:com.aristoula.persistence.messages.proto.Get)
    private static final com.aristoula.persistence.messages.proto.Messages.Get DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aristoula.persistence.messages.proto.Messages.Get();
    }

    public static com.aristoula.persistence.messages.proto.Messages.Get getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Get>
        PARSER = new com.google.protobuf.AbstractParser<Get>() {
      public Get parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Get(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Get> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Get> getParserForType() {
      return PARSER;
    }

    public com.aristoula.persistence.messages.proto.Messages.Get getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aristoula_persistence_messages_proto_CounterChanged_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aristoula_persistence_messages_proto_CounterChanged_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aristoula_persistence_messages_proto_Get_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aristoula_persistence_messages_proto_Get_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022(com.aristoula.persiste" +
      "nce.messages.proto\"\242\001\n\016EntityEnvelope\022\n\n" +
      "\002id\030\001 \001(\003\022D\n\007payload\030\002 \001(\01623.com.aristou" +
      "la.persistence.messages.proto.CounterOp\022" +
      "\017\n\007ohField\030\003 \001(\t\022\025\n\rsomeOtherShit\030\004 \001(\003\022" +
      "\026\n\016MoreShitToCome\030\005 \001(\t\"5\n\016CounterChange" +
      "d\022\r\n\005delta\030\001 \001(\005\022\024\n\014anotherField\030\002 \001(\t\"." +
      "\n\003Get\022\021\n\tcounterId\030\001 \001(\003\022\024\n\014anotherField" +
      "\030\002 \001(\t*)\n\tCounterOp\022\r\n\tINCREMENT\020\000\022\r\n\tDE" +
      "CREMENT\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aristoula_persistence_messages_proto_EntityEnvelope_descriptor,
        new java.lang.String[] { "Id", "Payload", "OhField", "SomeOtherShit", "MoreShitToCome", });
    internal_static_com_aristoula_persistence_messages_proto_CounterChanged_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_aristoula_persistence_messages_proto_CounterChanged_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aristoula_persistence_messages_proto_CounterChanged_descriptor,
        new java.lang.String[] { "Delta", "AnotherField", });
    internal_static_com_aristoula_persistence_messages_proto_Get_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_aristoula_persistence_messages_proto_Get_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aristoula_persistence_messages_proto_Get_descriptor,
        new java.lang.String[] { "CounterId", "AnotherField", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
